language: node_js
node_js:
  - 0.8
services:
  - mongodb
before_script:
  - mongo quicklog-test --eval 'db.addUser("user", "password");'
notifications:
  email:
    recipients:
      - roy@roylines.co.uk
      - james@thebloomers.co.uk
    on_success: [change]
    on_failure: [always]